FROM node:18-alpine

# Install necessary dependencies for Puppeteer
RUN apk add --no-cache \
  chromium \
  nss \
  freetype \
  freetype-dev \
  harfbuzz \
  ca-certificates \
  ttf-freefont \
  dumb-init

# Set the Puppeteer environment variables
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false \
    PUPPETEER_CACHE_DIR=/usr/src/app/.cache

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

# Ensure Puppeteer installs its own version of Chromium
RUN npx puppeteer install

# Expose the port the app runs on
EXPOSE 5000

# Use dumb-init to handle process signals correctly
ENTRYPOINT ["/usr/bin/dumb-init", "--"]

# Run the application
CMD ["npm", "start"]
